### ISSUE TITLE
mapreads.py hard-codes # of cores to 1 for bowtie2? 

### ISSUE THREAD

**Issue by ribonucleo** [UCSC-LoweLab/tRAX#15]

**Comment by ribonucleo** [comment]
Or rather, whenever bowtie2 is called, the numcores doesn't seem to be included in the function call to run bowtie2 (I don't know where the function is ultimately used downstream, but for my purposes I just updated the default in the function definition to my liking)

**Comment by patriciaplchan** [comment]
How do you run mapreads.py? If you run it as a standalone tool, it will use the default value of numcores (which is 1) for execution because that is mainly for testing purpose. We suggest running the whole analysis pipeline by using processsamples.py which will include the execution of mapreads.py. Multiple cores will be used in that case as specified in the options. For more information on using tRAX, please check out http://trna.ucsc.edu/tRAX/.

**Comment by andrewdholmes** [comment]
The way multiple cores is implemented for mapping is to run multiple bowtie2 mappings in parallel rather than using multiple cores for a single mapping.
