### ISSUE TITLE
quickdb.bash

### ISSUE THREAD

**Issue by ashafik1** [UCSC-LoweLab/tRAX#18]
Hi there, 

When I try to run the bash script I get the following errors:

node04:[bin] % ./quickdb.bash mm10
/rnadb
Generating GTF
./quickdb.bash: line 92: /rnadb/genes.gtf: No such file or directory
Generating GTF Done
Generating gtRNAdb
/rnadb/tse.tar.gz: No such file or directory
tar (child): /rnadb/tse.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove ‘/rnadb/tse.tar.gz’: No such file or directory
Generating gtRNAdb Done
Generating Fasta
/rnadb/genome.2bit: No such file or directory
mustOpen: Can't open /rnadb/genome.fa to write: No such file or directory
Generating Fasta Done
Starting TRAX makernadb
./quickdb.bash: line 126: maketrnadb.py: command not found

Thanks

**Comment by alba1735** [comment]
Hello,

You need to specify a folder you want to build the db into otherwise it defaults to /rnadb (for docker compatibility reasons) which probably doesn’t exist or you don’t have access to on your system. If you try running the command "./quickdb.bash mm10 rnadb” instead it should create a folder called rnadb with files in it from wherever you run the command. If you still receive an error, try running “mkdir rnadb” first to create the directory for the files then try running again. Sorry for the inconvenience I will update the documentation accordingly. Please let me know if you have any other issues.

-Alex Bagi

**Comment by ashafik1** [comment]
Thank you, looks like that solved the problem. I appreciate the fast response!

**Comment by ashafik1** [comment]
I'm not sure if this may be a specific error on my end, but I get another error message:

Generating GTF
Generating GTF Done
Generating gtRNAdb
Generating gtRNAdb Done
Generating Fasta
Generating Fasta Done
Starting TRAX makernadb
Traceback (most recent call last):
  File "maketrnadb.py", line 188, in <module>
    getmaturetrnas.main(trnascan=[scanfile], genome=genomefile,gtrnafa=gtrnafafile,namemap=namemapfile, bedfile=dbdirectory+dbname+"-maturetRNAs.bed",maturetrnatable=dbdirectory+dbname+"-trnatable.txt",trnaalignment=transcriptstk,locibed=dbdirectory+dbname+"-trnaloci.bed",maturetrnafa=dbdirectory+dbname+"-maturetRNAs.fa",cmmodel = maturemodel, prokmode = prokmode)
  File "/mnt/icebreaker/data2/home/ashafik/trax/tRAX-master/getmaturetrnas.py", line 125, in main
    seqfile = tempmultifasta(((currtrans.name, currtrans.getmatureseq(addcca = not prokmode)) for currtrans in alltrnas))
  File "/mnt/icebreaker/data2/home/ashafik/trax/tRAX-master/trnasequtils.py", line 88, in tempmultifasta
    fafile = tempfile.NamedTemporaryFile(suffix=".fa")
NameError: global name 'tempfile' is not defined
