### ISSUE TITLE
isodecoder copy number

### ISSUE THREAD

**Issue by dylansosa** [UCSC-LoweLab/tRAX#26]
Hey all,

I am interested in knowing the isodecoder copy number from which certain fragments are derived. For example, in the count output I know:

"tRNA-Ala-AGC-1-1_wholeprecounts"
"tRNA-Ala-AGC-1-1_partialprecounts"
"tRNA-Ala-AGC-1-1_trailercounts"

Which shows counts for tRNA-Ala-AGC-1-1. However, in the case of wholecounts, five and three prime fragments, other, and antisense I only know tRNA-iMet-CAT-2, but not which copy the fragments come from as shown below:

"tRNA-iMet-CAT-2_wholecounts"
"tRNA-iMet-CAT-2_fiveprime"
"tRNA-iMet-CAT-2_threeprime"
"tRNA-iMet-CAT-2_other"
"tRNA-iMet-CAT-2_antisense"

Is there a way to know which copy of a tRNA the fragments are derived from? i.e. tRNA-iMet-CAT-2-X_antisense to indicate if it is from CAT-2-1 or CAT-2-2.

Thanks!

**Comment by patriciaplchan** [comment]
Because all the gene loci for tRNA-iMet-CAT-2 isodecoder have identical sequence, the tRNA transcripts and derived fragments will also be identical. There isn't any way to know which gene locus produces the fragments just by using typical small RNA-seq or tRNA-seq. If your experiment is specifically designed to identify tRNA fragments at gene locus level, you will likely need to analyze the data with tools designed for such an experiment that is not supported by tRAX.

**Comment by dylansosa** [comment]
Hi Patricia,

Thanks for your response! I suspected that was the case--I realize now I was confused by the _partialprecounts and _trailercounts, etc having the locus number and started to conflate them.

One last question, are the _antisense counts also fragments?

**Comment by dylansosa** [comment]
Hi Patricia,

Thanks for your response! I suspected that was the case--I realize now I was confused by the _partialprecounts and _trailercounts, etc having the locus number and started to conflate them.
